- name: Build Wheel Cache
  hosts: all
  strategy: free  # noqa: run-once[play]

  pre_tasks:
    - name: Set fact for wheel dir
      set_fact:
        wheel_dir: /opt/wheel/workspace

  roles:
    - build-wheel-cache
