- name: Collect Wheel Cache Build Logs
  hosts: all
  tasks:
    - name: Ensure build logs directory exists
      file:
        path: "{{ zuul.executor.log_root }}/{{ wheel_python }}"
        state: directory
      delegate_to: localhost

    - name: Compress build logs
      community.general.archive:
        dest: '~/logs/build-logs.tar.bz2'
        path: '~/logs/build'
        format: bz2

    - name: Remove uncompressed logs
      file:
        state: absent
        path: '~/logs/build'

    - name: Collect final logs
      ansible.posix.synchronize:
        dest: "{{ zuul.executor.log_root }}/{{ wheel_python }}"
        mode: pull
        src: ~/logs/
        verify_host: true
