- name: Send Release Announcement
  hosts: all
  tasks:
    - name: Send release announcement
      command: >
        src/opendev.org/openstack/releases/tools/announce.sh
          src/{{ zuul.project.canonical_name }} {{ zuul.tag }}
