- name: Prepare Release Announcement Environment
  hosts: all
  roles:
    - role: bindep
      bindep_profile: test
      bindep_dir: src/opendev.org/openstack/releases
    - role: ensure-tox
      ensure_global_symlinks: true
    - ensure-virtualenv
    - revoke-sudo
