#!/usr/bin/env python3

import configparser
import os
import os.path
import subprocess
import sys
import textwrap

if len(sys.argv) != 3:
    print('Extracts the env_dir used for the releasenotes tox testenv\n')
    print('Usage:\n')
    print(f'  {os.path.basename(sys.argv[0])} <dir> <test_env>')
    sys.exit(1)

root = os.path.abspath(sys.argv[1])
test_env = sys.argv[2]

if not os.path.exists(root):
    print(f'{sys.argv[1]} is not a valid path', file=sys.stderr)
    sys.exit(1)

try:
    proc = subprocess.run(
        ['tox', '-c', root, '-e', test_env, 'config'],
        capture_output=True,
        check=True,
    )
except subprocess.CalledProcessError as e:
    print(
        'Got error attempting to fetch config for releasenotes testenv:\n',
        file=sys.stderr,
    )
    print(
        textwrap.indent(e.output.decode(errors='ignore'), prefix='\t'),
        file=sys.stderr,
    )
    print('\nExiting...', file=sys.stderr)
    sys.exit(1)

parser = configparser.ConfigParser()
parser.read_string(proc.stdout.decode(errors='replace'))
env_dir = parser.get('testenv:releasenotes', 'env_dir')
print(env_dir, end='')
