- name: Return Molecule Report As Zuul Artifact
  hosts: all
  tasks:
    - name: Return artifact to Zuul
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "Molecule report"
                url: "tox/reports.html"
                metadata:
                  type: html_report
