---

- name: Ensure that token is provided
  ansible.builtin.fail:
    msg: 'Specify token to access Galaxy server'
  when: ansible_galaxy_info.token is not defined

- name: Include role for pip
  ansible.builtin.include_role:
    name: ensure-pip

- name: Install ansible
  ansible.builtin.pip:
    name: ansible-core
    version: "{{ ansible_galaxy_version | default(omit) }}"
    virtualenv: "{{ ansible_galaxy_virtualenv_path }}"
    virtualenv_command: /usr/bin/python3 -m venv

- name: Fail if no tag version found
  ansible.builtin.fail:
    msg: "No tag was found in Zuul vars!"
  when: ansible_collection_version_tag == 'no_version'

- name: Create a directory for collection
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_galaxy_build_collection_path }}"

- name: Set galaxy.yml for right version from tag
  ansible.builtin.lineinfile:
    path: '{{ ansible_galaxy_collection_path }}/galaxy.yml'
    regexp: '^version:.*'
    line: 'version: {{ ansible_collection_version_tag }}'

- name: Build collection
  ansible.builtin.command: >-
    {{ ansible_galaxy_virtualenv_path }}/bin/ansible-galaxy collection build --output-path {{ ansible_galaxy_build_collection_path }} --force
  args:
    chdir: "{{ ansible_galaxy_collection_path }}"

- name: Publish content to Ansible Galaxy
  block:
    - name: Create ansible.cfg configuration file tempfile
      ansible.builtin.tempfile:
        state: file
        suffix: .cfg
      register: _ansiblecfg_tmp

    - name: Create ansible.cfg configuration file
      ansible.builtin.template:
        src: ansible.cfg.j2
        dest: "{{ _ansiblecfg_tmp.path }}"
        mode: "0600"

    - name: Get content of galaxy.yml
      ansible.builtin.slurp:
        src: "{{ ansible_galaxy_collection_path }}/galaxy.yml"
      register: galaxy_vars

    - name: Parse yaml into variable
      ansible.builtin.set_fact:
        galaxy_yaml: "{{ galaxy_vars['content'] | b64decode | from_yaml }}"

    - name: Publish collection to Ansible Galaxy / Automation Hub
      environment:
        ANSIBLE_CONFIG: "{{ _ansiblecfg_tmp.path }}"
      ansible.builtin.command: >-
        {{ ansible_galaxy_virtualenv_path }}/bin/ansible-galaxy collection publish -vvv
        {{ ansible_galaxy_build_collection_path }}/{{ galaxy_yaml.namespace }}-{{ galaxy_yaml.name }}-{{ ansible_collection_version_tag }}.tar.gz

  always:
    - name: Shred ansible-galaxy credentials
      ansible.builtin.command: "shred {{ _ansiblecfg_tmp.path }}"
