- name: Prepare JavaScript Dev Environment
  hosts: all
  roles:
    - role: bindep
      bindep_profile: test
      bindep_dir: "{{ zuul_work_dir }}"
    - test-setup
    - ensure-nodejs
    - ensure-yarn
    - revoke-sudo
    - ensure-javascript-packages
