# Project pipeline definition for openstack-zuul-jobs
- project:
    templates:
      - publish-tox-docs-infra

    check:
      jobs:
        - opendev-buildset-registry
        - project-config-grafana:
            files:
              - playbooks/grafana
        - openafs-rpm-package-build-centos-9-stream-x86
        - openafs-rpm-package-build-centos-9-stream-arm64
        - openstack-zuul-jobs-linters
        - build-wheel-cache-centos-9-stream:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-debian-bullseye:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-ubuntu-bionic:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-ubuntu-focal:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-ubuntu-jammy:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
    check-arm64:
      jobs:
        - build-wheel-cache-centos-9-stream-arm64:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-debian-bullseye-arm64:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-ubuntu-focal-arm64:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-ubuntu-jammy-arm64:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
    gate:
      jobs:
        - openafs-rpm-package-build-centos-9-stream-x86
        - openafs-rpm-package-build-centos-9-stream-arm64
        - openstack-zuul-jobs-linters
    promote:
      jobs:
        - openafs-rpm-package-build-promote
